name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build Challenges
      run: cd stories && npm install && npm run build

    - name: Build Centering
      run: cd centering && npm install && npm run build

    - name: Build Sidenav
      run: cd sidenav && npm install && npm run build
      
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: gui-challenges
